name: Build and Deploy Jupyter Book

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install ghp-import

    - name: Build Jupyter Book
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html

